version: '3.8'

services:
  # Сервис для запуска Python-скрипта
  python-app:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    environment:
      - YANDEX_API_KEY=${YANDEX_API_KEY}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
      - LOG_LEVEL=${LOG_LEVEL}
    restart: unless-stopped
    # Добавляем healthcheck для проверки работоспособности
    healthcheck:
      test: ["CMD", "pgrep", "cron"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx для раздачи статических файлов
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - python-app
    restart: unless-stopped 