services:
  # Сервис для запуска Python-скрипта
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    environment:
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - API_KEY=${API_KEY}
    restart: always
    ports:
      - "5003:5003"
    command: python fetch_coordinates.py --flask
    

  # Nginx для раздачи статических файлов
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "9980:80"
    volumes:
      - nginx_cache:/var/cache/nginx
      - ./logs:/usr/share/nginx/html/logs
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - python-app
    restart: always

volumes:
  nginx_cache: 