version: '3.8'

services:
  # Сервис для запуска Python-скрипта
  python-app:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    environment:
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - API_KEY=${API_KEY}
    restart: unless-stopped
    # Добавляем healthcheck для проверки работоспособности
    healthcheck:
      test: ["CMD", "pgrep", "cron"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx для раздачи статических файлов
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "9980:80"
    volumes:
      - ./static:/usr/share/nginx/html:ro
    user: nginx
    restart: unless-stopped 